[workspace]
resolver = "2"
members = ["crates/geom", "crates/aero", "crates/sim", "crates/cli", "crates/panel"]

[workspace.package]
version = "0.2.0"
edition = "2021"
license = "GPL-3.0-or-later"
authors = ["西濱大将 (NISHIHAMA Daisuke) <daisukenishihama63@gmail.com>"]
repository = "https://github.com/ddd3h/ignisyeet"

[workspace.dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
clap = { version = "4", features = ["derive"] }
rayon = "1"
geom = { path = "crates/geom" }
aero = { path = "crates/aero" }
sim = { path = "crates/sim" }
faer = { version = "0.24", default-features = false, features = ["std", "rayon"] }
panel = { path = "crates/panel" }
indicatif = "0.17"
console = "0.15"
rand = "0.9"
rand_chacha = "0.9"
rand_distr = "0.5"

[profile.release]
opt-level = 3
